services:
  - type: web
    name: imaralink
    env: node
    plan: free
    buildCommand: "npm ci && npm run build"
    startCommand: "npm run start"
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_PUBLIC_SITE_URL
        value: https://imaralink.onrender.com
